replicaCount: 1
app:
  version: 1
image:
  repository: verchol/webinardemo
  tag: latest1
  pullPolicy: Always
service:
  name: webinar
  type: LoadBalancer
  externalPort: 80
  internalPort: 3000
ingress:
  enabled: false
  hosts:
  - chart-example.local
  annotations: null
  tls: null
resources: {}
images:
  tag: latest1
